### ISSUE TITLE
Which browsers do you support?

### ISSUE THREAD

**Issue by jslegers** [sudhirj/simply-deferred#27]
I can't find any info on which browsers are supported by Simply Deferred.

Could you please provide me this info any perhaps add it somewhere in your documentation?

**Comment by sudhirj** [comment]
I'm not actually sure what this list would be. It should work fine on all modern browsers, and even the older ones - the CoffeeScript transpiler does a pretty good job of generating compatible code. I think it's safe to say that it's supported pretty much everywhere.

If there's a problem in any browser, it might make sense to file an issue, I'll treat it as a bug.
